### ISSUE TITLE
ImportError: No module named 'ConfigParser'

### ISSUE THREAD

**Issue by skywebro** [theatlantic/django-mysqlndb-backend#3]
I get this error when trying to install it using pip, python version 3.5.0

**Comment by fdintino** [comment]
This change should do it. There were some minor incompatibilities with python 3 within django-mysqlndb-backend itself, but also the [MySQL-python](https://pypi.python.org/pypi/MySQL-python) dependency is not python 3 compatible (which is where your ConfigParser error was coming from), whereas [mysqlclient](https://pypi.python.org/pypi/mysqlclient) is. You may need to uninstall MySQL-python before reinstalling django-mysqlndb-backend in order for it to pull in the correct package.

Unfortunately someone created a PyPI package for this library on our behalf (it appears that it might be @enriqueaf ?) So unless they give the PyPi user "theatlantic" write access to that package you will just have to pip install from source. I recommend pinning it to a tag, e.g.:

```
pip install -e git+git://github.com/theatlantic/django-mysqlndb-backend.git@v1.1.0#egg=django-mysqlndb-backend
```

**Comment by ehsanamd** [comment]
But it's not working :( @fdintino

**Comment by fdintino** [comment]
@ehsanamd You're going to have to be a bit more specific.

**Comment by enriqueaf** [comment]
Hi! I jumped on to this issue by coincidence. @fdintino just as side note, I am not the one who created that project in pypi :D
